dada2-export-asv-table_wc: '{fs_prefix}/{df}/feature_tables/{sample_set}/{ft_name}/asv_table.rds'
dada2-export-asv-table_sample_set_tsv_wc: '{fs_prefix}/{df}/dada2/{sample_set}/sample_set.tsv'
dada2-export-asv-table_sample_set_dir_wc: '{fs_prefix}/{df}/dada2/{sample_set}/'

dada2-export-asv-table_ft_meta_dir_wc: '{fs_prefix}/{df}/feature_tables/{sample_set}/{ft_name}/'


dada2-export-asv-table_source_wc: '{fs_prefix}/{df}/dada2/{sample_set}/learn_errors__{learn_errors_preset}/core_algo__{core_algo_preset}/merged__{merged_preset}/nonchim__{nonchim_preset}/seqtab.rds'
