dada2-derep-infer-merge_sample_set_tsv_wc: '{fs_prefix}/{df}/dada2/{sample_set}/sample_set.tsv'
dada2-derep-infer-merge_sample_set_dir_wc: '{fs_prefix}/{df}/dada2/{sample_set}/'
dada2-derep-infer-merge_wc :               '{fs_prefix}/{df}/dada2/{sample_set}/learn_errors__{learn_errors_preset}/core_algo__{core_algo_preset}/merged__{merged_preset}/seqtab.rds'